### ISSUE TITLE
Revoke token is available after long time (tens of minutes)

### ISSUE THREAD

**Issue by rBunin** [ytsaurus/ytsaurus#468] opened 2024-03-18 11:19 UTC
It was reported that after revoking token it is still available in 10-15 minutes after revoke. We need to reproduce this behaviour and find out if it cashed or something.

**Comment by Krock21** [comment] 2024-04-19 20:26
Reproduced the issue in minikube. The token is available until proxy restart

The reason is because AuthCache ignores an error thrown by CypressAuthenticator. This is a bug

A PR was created

**Comment by Krock21** [comment] 2024-05-13 07:54
Commits were merged to stable/23.2, stable/24.2 and main branches
Nightly images contain fixes already, other images should have them later

**Closed by Krock21** 2024-05-13 07:54 UTC
Labels: assigned
