### ISSUE TITLE
SPYT fails to read Struct type columns

### ISSUE THREAD

**Issue by Hattonuri** [ytsaurus/ytsaurus#186] opened 2023-11-23 11:34 UTC
when i do df.select('field.field1').show() i get
Can't extract value from field#3: need struct type but got yson

**Comment by alextokarew** [comment] 2023-11-23 11:44
Have you specified `spark.yt.read.parsingTypeV3.enabled=true` option?

**Comment by Hattonuri** [comment] 2023-11-23 14:31
No i haven't.

After i specify it, and use df.select('limits.lower_limit').show() i get
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

I also tried df.select('limits.[1]').show() and got
No such struct field [1] in lower_limit, upper_limit

Table to reproduce
[table_to_show.txt](https://github.com/ytsaurus/ytsaurus/files/13451030/table_to_show.txt)

**Comment by alextokarew** [comment] 2023-11-23 14:37
Does your table has strict schema? SPYT works only with tables that has strict schema.

**Comment by Hattonuri** [comment] 2023-11-23 15:06
Yes,
Full schema from attributes is 
"Type": [
            "StructType",
            [
                [
                    "limits",
                    [
                        "OptionalType",
                        [
                            "StructType",
                            [
                                [
                                    "lower_limit",
                                    [
                                        "OptionalType",
                                        [
                                            "DataType",
                                            "Decimal",
                                            "35",
                                            "18"
                                        ]
                                    ]
                                ],
                                [
                                    "upper_limit",
                                    [
                                        "OptionalType",
                                        [
                                            "DataType",
                                            "Decimal",
                                            "35",
                                            "18"
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ],

**Comment by alextokarew** [comment] 2023-11-27 07:21
Yes, I've reproduced this and got the same error. It really looks like a bug, we'll fix it in the following release.

**Comment by alextokarew** [comment] 2023-11-27 15:25
The fix will be included in the next release. The `df.select('limits.lower_limit').show()` code should work with it.

**Comment by alextokarew** [comment] 2023-11-30 13:03
Fixed in 1.75.3 SPYT Release

**Closed by alextokarew** 2023-11-30 13:03 UTC
Labels: spyt
