### ISSUE TITLE
Query Tracker Fails to Update Query State Due to uint32 Range Issue

### ISSUE THREAD

**Issue by nordikafiles** [ytsaurus/ytsaurus#77] opened 2023-07-29 18:23 UTC
The Query Tracker is experiencing a problem where it fails to correctly update the state of a query. The underlying issue appears to be related to a Value is out of range to fit into uint32 error.

Details of the error message:
```
2023-07-29 18:12:40,637961 E QueryHandler Failed to write query state, backing off (QueryId: b9f81cb4-697f258f-a2ff28f2-4131ab67, Engine: Yql)\nValue is out of range to fit into uint32\n origin qt-0.query-trackers.yt.svc.cluster.local (pid 1, thread Control, fid fffef47e368c12c8)\n datetime 2023-07-29T18:12:40.637648Z\n Control fffef47e368c12c8 2a276c92-c52337af-5a72971c-c2600800
```

**Steps to Reproduce**:

Run the following YQL query:
```sql
use main;

select
    received_at,
    Yson::YPath(`json`, "/data/E") as E
from (
    select * from range(`//home/table1`)
    union all
    select * from range(`//home/table2`)
)
limit 10
```

**Expected Result**: The Query Tracker should be able to accurately update the state of each query.

**Actual Result**: The Query Tracker fails to update the state of a query due to a Value is out of range to fit into uint32 error.

Please look into this issue at the earliest convenience and let us know if you need any further information to aid your investigation. Thank you.

**Comment by zlobober** [comment] 2023-11-17 23:58
There were various improvements in QT around state management since the time of report. I'd suggest collecting the debug log of query tracker next time such issue reproduces.
Unfortunately there is not information to debug this issue, so I'm closing this one. Please open a new issue in case of reproduce.

**Closed by zlobober** 2023-11-17 23:58 UTC
Labels: bug, yql
